### ISSUE TITLE
Compile the Kubernetes e2e test

### ISSUE THREAD

**Issue by iXinqi** [kubernetes-sigs/windows-operational-readiness#3]
1) Integrate the binary e2e.test to our dockerfile image. check the architecture compile, will need to build cross for linux/amd64
2) Run on the kind cluster.
3) Run on Windows cluster

Resources:

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md

**Comment by knabben** [comment]
add a readme with the instructions
