### ISSUE TITLE
when running e2e tests, the test case being executed are stuck and are not proceeding, also there is no option of adding verbose

### ISSUE THREAD

**Issue by pramitagautam** [kubernetes-sigs/windows-operational-readiness#52]
<img width="1103" alt="Screenshot 2023-04-12 at 9 01 58 PM" src="https://user-images.githubusercontent.com/113517620/231507574-298532d7-7f57-4892-8244-f1f383b84839.png">

Even if the test case is running, no output is being observed on the screen, also no option of adding verbose.
But the Kubernetes e2e tests have this option (--ginkgo.v)
```
./e2e.test --provider=local --kubeconfig=/Users/gpramita/.kube/config --node-os-distro=windows --ginkgo.v --ginkgo.focus="services"
```

**Comment by tzifudzi** [comment]
Going through an exercise to cleanup issues. We can close this in favour of tracking through 2 separate issues I created
1. https://github.com/kubernetes-sigs/windows-operational-readiness/issues/75
2. https://github.com/kubernetes-sigs/windows-operational-readiness/issues/69
