### ISSUE TITLE
SPECS/networkpolicy, networking 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/windows-operational-readiness#57]
me and pramita will do this part of #56

**Comment by tzifudzi** [comment]
Going through an exercise of cleaning up issues. We can close this in favour of tracking through 
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/65
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/71
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/72

**Comment by tzifudzi** [comment]
/close
Tracking in below issues
- #65
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/71
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/72
