### ISSUE TITLE
remove linters or fix em

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/windows-operational-readiness#90]
### Describe the bug. What is the current and expected behaviour?

looks like on simple PRs we get some verify/lint errors.  lets either remove the lints if unneeded or fix them.

Example https://github.com/kubernetes-sigs/windows-operational-readiness/pull/81 
### How to reproduce it (as minimally and precisely as possible)?

make a PR :)  
As an example make a PR like the one above and you'll see the lint failures.  probably they are referencing pre-exisiting lint issues we've never tackled

**Comment by yussufsh** [comment]
I think this is already fixed.

**Comment by tzifudzi** [comment]
Yes, this was fixed. Sorry I saw this late. See issue https://github.com/kubernetes-sigs/windows-operational-readiness/issues/78 and PR https://github.com/kubernetes-sigs/windows-operational-readiness/pull/87
